/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'githubUrl' : IDL.Text,
  'email' : IDL.Text,
  'linkedInUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'githubUrl' : IDL.Text,
    'email' : IDL.Text,
    'linkedInUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };